### ISSUE TITLE
astartectl-housekeeping.pub structure error!

### ISSUE THREAD

**Issue by BradPrit09** [astarte-platform/astarte#156]
After Installations, when I do ```astartectl housekeeping realms create test --housekeeping-url http://localhost:4001/ -p test_realm.key.pub -k compose/astarte-keys/housekeeping.pub```, it result in structure error in the housekeeping.pub file probably
**Error**
```asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompo
nd:true}) {optional:false explicit:false application:false private:false defaul
Value:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @2
```

**Comment by rbino** [comment]
It's actually an error in the documentation, you should use
```
[...] -k compose/astarte-keys/housekeeping.key
```
instead of
```
[...] -k compose/astarte-keys/housekeeping.pub
```
Let me know if using `housekeeping.key` fixes the problem and I will fix the documentation.

**Comment by BradPrit09** [comment]
When I do 

1. 

``` awk '{printf "%s\\n", $0}' test_realm.key.pub > test_realm.key.pub.api```
```
awk: '{printf
awk: ^ invalid char ''' in expression
```
2.
```curl -X POST http://localhost:4001/v1/realms -H "Authorization: Bearer $(./generate-astarte-credentials -t housekeeping -p compose/astarte-keys/housekeeping.key)" -H "Content-Type: application/json" -d "{\"data\":{\"realm_name\": \"test\", \"jwt_public_key_pem\": \"$(cat test_realm.key.pub.api)\"}}"```
Curl fails to connect to localhost port 4001. I also checked that Is port that port is utilized by windows but this I could find any.

**Comment by BradPrit09** [comment]
> It's actually an error in the documentation, you should use
> 
> ```
> [...] -k compose/astarte-keys/housekeeping.key
> ```
> 
> instead of
> 
> ```
> [...] -k compose/astarte-keys/housekeeping.pub
> ```
> 
> Let me know if using `housekeeping.key` fixes the problem and I will fix the documentation.

When I do

awk '{printf "%s\\n", $0}' test_realm.key.pub > test_realm.key.pub.api

awk: '{printf
awk: ^ invalid char ''' in expression
curl -X POST http://localhost:4001/v1/realms -H "Authorization: Bearer $(./generate-astarte-credentials -t housekeeping -p compose/astarte-keys/housekeeping.key)" -H "Content-Type: application/json" -d "{\"data\":{\"realm_name\": \"test\", \"jwt_public_key_pem\": \"$(cat test_realm.key.pub.api)\"}}"
Curl fails to connect to localhost port 4001. '''conn refused''' I also checked that Is port that port is utilized by windows but this I could find any.

**Comment by BradPrit09** [comment]
I have checked the status of the containers , the astarte/astarte_housekeeping_api:snapshot to be specific. The container restarts every second. Is this the real issue that I cannot curl post  to the housekeeping api?

**Comment by rbino** [comment]
Hi @BradPrit09,
it could be possible that your problems were due to the fact that you installed astarte just as we were moving things around. Now that should be over, so you can try to start again from a clean state and check if things are working now.
If something is still not working please let us know.
