### ISSUE TITLE
Handle hyphens in interface_name

### ISSUE THREAD

**Issue by matt-mazzucato** [astarte-platform/astarte#184]
Astarte core currently allows hyphens in the interface_name according to https://github.com/astarte-platform/astarte_core/pull/10
As discussed in https://github.com/astarte-platform/astarte_core/issues/7, the new naming convention must be handled while mapping the interface onto the table name.

**Comment by bettio** [comment]
Duplicate of https://github.com/astarte-platform/astarte/issues/96
