### ISSUE TITLE
AppEngine: crash on not server owned interfaces POST/PUT requests

### ISSUE THREAD

**Issue by Pavinati** [astarte-platform/astarte#264]
Sending a POST (or PUT) request on a non server owned interface path crashes the API

Example
`POST https://my.astarte.instance.com/appengine/v1/test/devices/912p01EGRqe_ER1lLDn9lA/interfaces/org.astarte-platform.genericsensors.Values/my_sensor/value`

Expected result
405 Method Not Allowed

Actual result
500 - Internal server error

**Comment by rbino** [comment]
Closed by #706
