### ISSUE TITLE
Astarte might lose VerneMQ events and represent a wrong connection state

### ISSUE THREAD

**Issue by drf** [astarte-platform/astarte#270]
In some unlucky cases, Astarte might lose some connection/disconnection events from VerneMQ (e.g.: VerneMQ restarts, a previously connected device doesn't reconnect). In those cases, the internal device state is represented as `connected=True` instead of `connected=False`.

Astarte should have a way to catch these occurrences and ensure the device connection state is always consistent.

**Comment by bettio** [comment]
This bug is a duplicate of https://github.com/astarte-platform/astarte/issues/305 which contains a better description of the issue.
