### ISSUE TITLE
Enhance logging during health checks

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#296]
Right now, every `get_health` call makes a query that produces this Cassandra warning:
```
"Aggregation query used without partition key"
```

Since health queries are done frequently, this pollutes logs and makes it harder to make important things stand out.

We can either suppress that specific warning or change the query that is used for health checks.

**Comment by rbino** [comment]
Another aspect of this is logging in the APIs: right now every `GET /health` request generates 3 entries in the log and basically decreases a lot the signal to noise ratio of logs.
We should probably tackle that in [this way](https://elixirforum.com/t/disable-logging-on-specific-route/622/2) i.e., move `plug PlugLoggerWithMeta` from `Endpoint` to `Router` inside the `:api` pipeline.
Note that doing so will probably make the APIs stop logging requests that are not handled by a scope (e.g. something like `/unexisting`).

**Comment by drf** [comment]
> Note that doing so will probably make the APIs stop logging requests that are not handled by a scope (e.g. something like /unexisting).

I don't see this as an issue. In production deployments, APIs will be exposed in front of a reverse proxy/load balancer which should log such requests. Moreover, a production deployment will probably want to ban from the load balancer any route which doesn't match valid paths. This could also be an enhancement for what concerns Ingress objects in the Operator.

**Comment by rbino** [comment]
The first part is already tracked by #420 and the second one was fixed in #440, so we can close this
