### ISSUE TITLE
When deleting an aggregate interface, the associated table in Cassandra is not deleted

### ISSUE THREAD

**Issue by drf** [astarte-platform/astarte#311]
DELETE-ing an aggregate interface triggers the following error when trying to install it again:

```
terminating\n** (MatchError) no match of right hand side value: %{acc: [], msg: \"Cannot add already existing table
```

Instead, DELETE should clean up all references, including dropping the associated table in Cassandra

**Comment by bettio** [comment]
This issue was a Cassandra internal issue.
Closing this bug as invalid.

**Comment by bettio** [comment]
See also https://github.com/astarte-platform/astarte/issues/312 .
