### ISSUE TITLE
Wait for schema consensus

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte#312]
Each schema change statement should be executed only when Cassandra has reached schema consensus.
Schema changes without a consensus might bring to an undefined behavior.

Proposed solution:
1. Check (and wait) consensus using `system.peers.schema_version` and `system.local.schema_version` columns.
2. Execute schema change.
3. Check (and wait) consensus again.

**Comment by bettio** [comment]
See also https://github.com/lexhide/xandra/issues/181 .

**Comment by rbino** [comment]
Closed by #350
