### ISSUE TITLE
Astarte in 5 minutes doc page assumes astartectl is already installed

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte#332]
[Astarte in 5 minutes](https://docs.astarte-platform.org/snapshot/010-astarte_in_5_minutes.html) makes the assumption that astartectl is already installed, it might be easier to newcomers explaining how to install it before starting.
Bonus point: some users might not be aware of `$PATH`

**Comment by rbino** [comment]
This is fixed now, closing this
