### ISSUE TITLE
Time for new trigger to progagate

### ISSUE THREAD

**Issue by shortwavedave** [astarte-platform/astarte#361]
The online docs (https://docs.astarte-platform.org/snapshot/060-using_triggers.html#installing-a-trigger) say:

"If a Trigger shows as installed, it will eventually be loaded."

How long is eventually? a couple seconds, minutes?

**Comment by rbino** [comment]
Hi @shortwavedave ,
in the current implementation the time is 10 minutes (i.e., if a device already has a Data Updater process started in Data Updater Plant, any new installed trigger will be reloaded at most 10 minutes later).

I will leave this issue open to track the addition of this interval to the documentation.

**Comment by shortwavedave** [comment]
@rbino Thanks, good to know!

**Comment by rbino** [comment]
The propagation time is now mentioned in the documentation, we can close this
