### ISSUE TITLE
What is match_path format

### ISSUE THREAD

**Issue by shortwavedave** [astarte-platform/astarte#362]
I get this error from astarte when trying to install a trigger:

`b'{"errors":{"simple_triggers":[{"match_path":["has invalid format"]}]}}'`

My match_path is this:

`"match_path": "/a42ce283-46b5-4545-8603-e2cd340326c8/45/trashLevel"`

What is wrong with the format? Here is a sample data point from a trigger:

```
{
  "timestamp": "2020-04-27T02:49:45.966Z",
  "event": {
    "value": 75,
    "type": "incoming_data",
    "path": "/a42ce283-46b5-4545-8603-e2cd340326c8/45/trashLevel",
    "interface": "..."
  },
  "device_id": "..."
}
```

This also doesn't work:

`/45/trashLevel`

I don't understand what the expected format is

**Comment by rbino** [comment]
Hi @shortwavedave,
can you please post the interface that is being targeted by this trigger?

**Comment by josephrodman** [comment]
I get the same error, the only match path that results in the trigger being created is "/*". Also, when the match_path is "/*", I can't post a trigger with a value_match_operator that is anything other than "*"...making the known_value irrelevent. I am trying to target the interface 'com.ilumenscloud.PSIValues', which is defined below:
`{                                                                                                                                                                     "interface_name": "com.ilumenscloud.PSIValues",                                                                                                                     "version_major": 0,                                                                                                                                                 "version_minor": 1,                                                                                                                                                 "type": "datastream",                                                                                                                                               "ownership": "device",                                                                                                                                              "aggregation": "individual",                                                                                                                                        "description": "PSI level time series.",                                                                                                                            "mappings": [                                                                                                                                                         {                                                                                                                                                                     "endpoint": "/%{uuid}/%{major}/psiLevel",                                                                                                                           "type": "double",                                                                                                                                                   "reliability": "unique",                                                                                                                                            "retention": "stored",                                                                                                                                              "database_retention_policy": "no_ttl",                                                                                                                              "expiry": 600000,                                                                                                                                                   "description": "PSI level from sensor",                                                                                                                             "doc": "PSI level from the sensor"                                                                                                                                }                                                                                                                                                                 ]                                                                                                                                                                 } `

**Comment by josephrodman** [comment]
@rbino

`{
  "action": {
    "http_post_url": "http://02b9-155-98-131-5.ngrok.io/astarte/triggers2"
  },
  "name": "trigger_example1",
  "simple_triggers": [
    {
      "interface_major": 0,
      "interface_name": "com.ilumenscloud.PSIValues",
      "match_path": "/a42ce283-46b5-4545-8603-e2cd340326c8/1/psiLevel",
      "on": "incoming_data",
      "type": "data_trigger",
      "value_match_operator": "*"
    }
  ]
}`

The response from astarte is: 
`{                                                                                                                                                                     "errors": {                                                                                                                                                           "simple_triggers": [                                                                                                                                                  {                                                                                                                                                                     "match_path": [                                                                                                                                                       "has invalid format"                                                                                                                                              ]                                                                                                                                                                 }                                                                                                                                                                 ]                                                                                                                                                                 }                                                                                                                                                                 }         `

**Comment by rbino** [comment]
Closing stale issue, please reopen it if it's still relevant
