### ISSUE TITLE
Fix Cassandra warning

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte#420]
Realm Management logs have a lot of noise due to 
`Warning from Cassandra: [<<"Aggregation query used without partition key">>]` warning.
A different query than `SELECT * FROM realms;` should be used instead.

**Comment by bettio** [comment]
`SELECT value FROM astarte.kv_store WHERE group=astarte AND key=schema_version` should be used instead.

**Comment by rbino** [comment]
Closed by #571
