### ISSUE TITLE
Data Updater Plant crashes when a path created trigger is installed on a datastream

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte#425]
Installing a "path created" data trigger on a datastream interface will cause a crash in data updater plant.
"Path created" triggers should be supported for datastreams too since a path might be created when using parametric paths.

Log:
level=error ts=2020-06-26T14:23:25.386+00:00 msg="GenServer {Registry.DataUpdater, {\"demo\", <<148, 194, 173, 165, 152, 34, 65, 41, 150, 97, 10, 217, 204, 172, 17, 202>>}} terminating\n** (FunctionClauseError) no function clause matching in Astarte.DataAccess.Data.fetch_property/5\n    (astarte_data_access 1.0.0-alpha.1) lib/astarte_data_access/data.ex:37: Astarte.DataAccess.Data.fetch_property({#PID<0.18988.0>, #Reference<0.1471858153.3274178561.246723>}, <<148, 194, 173, 165, 152, 34, 65, 41, 150, 97, 10, 217, 204, 172, 17, 202>>, %Astarte.Core.InterfaceDescriptor{aggregation: :individual, automaton: {%{{0, \"\"} => 1, {1, \"value\"} => 2}, %{2 => <<43, 50, 22, 72, 18, 150, 244, 159, 106, 76, 55, 49, 76, 170, 193, 112>>}}, interface_id: <<73, 127, 136, 37, 73, 251, 13, 93, 154, 249, 31, 186, 45, 17, 52, 211>>, major_version: 0, minor_version: 1, name: \"org.astarte-platform.genericsensors.Values\", ownership: :device, storage: \"individual_datastreams\", storage_type: :multi_interface_individual_datastream_dbtable, type: :datastream}, %Astarte.Core.Mapping{allow_unset: false, database_retention_policy: :no_ttl, database_retention_ttl: nil, description: nil, doc: nil, endpoint: \"/%{sensor_id}/value\", endpoint_id: <<43, 50, 22, 72, 18, 150, 244, 159, 106, 76, 55, 49, 76, 170, 193, 112>>, expiry: 0, explicit_timestamp: true, interface_id: <<73, 127, 136, 37, 73, 251, 13, 93, 154, 249, 31, 186, 45, 17, 52, 211>>, path: nil, reliability: :unreliable, retention: :discard, type: nil, value_type: :double}, \"/0001/value\")\n    (astarte_data_updater_plant 1.0.0-alpha.1) lib/astarte_data_updater_plant/data_updater/impl.ex:413: Astarte.DataUpdaterPlant.DataUpdater.Impl.handle_data/6\n    (astarte_data_updater_plant 1.0.0-alpha.1) lib/astarte_data_updater_plant/data_updater/server.ex:71: Astarte.DataUpdaterPlant.DataUpdater.Server.handle_cast/2\n    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4\n    (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6\n    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\nLast message: {:\"$gen_cast\", {:handle_data, \"org.astarte-platform.genericsensors.Values\", \"/0001/value\", <<27, 0, 0, 0, 1, 118, 0, 183, 74, 24, 170, 231, 252, 81, 64, 9, 116, 0, 65, 13, 244, 240, 114, 1, 0, 0, 0>>, \"demo-lMKtpZgiQSmWYQrZ-3899E43D4624CE-B907528F\", 15931804255397070}}\nState: %Astarte.DataUpdaterPlant.DataUpdater.State{connected: true, data_triggers: %{}, datastream_maximum_storage_retention: nil, device_id: <<148, 194, 173, 165, 152, 34, 65, 41, 150, 97, 10, 217, 204, 172, 17, 202>>, device_triggers: %{}, groups: [], initial_interface_exchanged_bytes: %{}, initial_interface_exchanged_msgs: %{}, interface_exchanged_bytes: %{}, interface_exchanged_msgs: %{}, interface_ids_to_name: %{}, interfaces: %{}, interfaces_by_expiry: [], introspection: %{\"org.astarte-platform.genericsensors.Values\" => 0}, introspection_triggers: %{}, last_device_triggers_refresh: 0, last_groups_refresh: 0, last_seen_message: 0, mappings: %{}, message_tracker: #PID<0.26132.0>, paths_cache: {32, %{}}, realm: \"demo\", total_received_bytes: 0, total_received_msgs: 0, volatile_triggers: []}" realm=demo device_id=lMKtpZgiQSmWYQrZzKwRyg module=gen_server function=error_info/7

**Comment by rbino** [comment]
Related to #138

**Comment by rbino** [comment]
Closed by #517
