### ISSUE TITLE
Make sure all SDKs are accepting http 301 status code from pairing.

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte#432]
Pairing should be allowed to redirect pairing requests to another URL using http 301 code.
In order to support this, all SDKs should support redirect.

**Comment by rbino** [comment]
- [x] esp32 (esp32 HTTP client follows redirects by default)
- [ ] Elixir (waiting for https://github.com/astarte-platform/astarte-device-sdk-elixir/pull/16)
- [ ] Qt5 (waiting for https://github.com/astarte-platform/astarte-device-sdk-qt5/pull/7)
- [x] Go (HTTP client follows redirects, max 10, by default)
- [x] Python (uses `requests`, which follows redirects by default)

**Comment by rbino** [comment]
All SDK now support this, closing this issue
