### ISSUE TITLE
Missing docker image for astarte-stream-qt5-test:0.11.3

### ISSUE THREAD

**Issue by davidebriani** [astarte-platform/astarte#474]
Following "Astarte in 5 minutes" guide, one should run the command:
```
docker pull astarte/astarte-stream-qt5-test:0.11.3
```
but that will result in `Error response from daemon: manifest for astarte/astarte-stream-qt5-test:0.11.3 not found: manifest unknown`.

astarte-stream-qt5-test is missing tag `0.11.3`

**Comment by davidebriani** [comment]
Same error for `astarte/astarte-stream-qt5-test:1.0.0-alpha.1`, following "Astarte in 5 minutes" docs for v1.0.0-beta.1

**Comment by rbino** [comment]
New releases have the correct tags so we can close this
