### ISSUE TITLE
ScyllaDB crashes when following 'Astarte in 5 minutes' guide

### ISSUE THREAD

**Issue by davidebriani** [astarte-platform/astarte#475]
Following the '5 minutes' guide, one tries to setup a local Astarte environment via docker-compose.
However it might happen that ScyllaDB crashes on startup with logs such as:

```
scylla: ../../src/core/reactor.cc:1297: seastar::reactor::reactor(unsigned int, seastar::reactor_backend_selector, seastar::reactor_config): Assertion `r >= 0' failed.
```

The most common cause is not enough request capacity in `/proc/sys/fs/aio-max-nr`.
The issue is that all this should be noted in the '5 minutes' guide, so that one knows he should try increasing that number: https://sort.veritas.com/public/documents/HSO/2.0/linux/productguides/html/hfo_admin_rhel/ch04s03.htm

A proper way to calculate the needed value can be found on ScyllaDB docs: https://github.com/scylladb/scylla/blob/master/docs/docker-hub.md#quick-start

**Comment by rbino** [comment]
This is [now documented](https://docs.astarte-platform.org/latest/010-astarte_in_5_minutes.html#before-you-begin) in Astarte in 5 minutes, so we can close this
