### ISSUE TITLE
AppEngine: filter query params with inconsistent behavior

### ISSUE THREAD

**Issue by davidebriani** [astarte-platform/astarte#553]
I'd like to report an odd behavior for the `since`, `sinceAfter` and `to` query params on interfaces data.

1) When querying a `datastream individual` interface, the `to` filter seems to work as a `<` comparison. I would expect a `<=` instead, given that `since` already works as a `>=` comparison and `sinceAfter` as `>`.
2) When querying a `datastream object` interface, the `since_after` filter seems to work as a `>=` comparison. I would expect a `>` instead, given that `since` already works as a `>=` comparison.

**Comment by rbino** [comment]
Possibly closed by #621, reopen if still relevant
