### ISSUE TITLE
Elixir.Astarte.DataUpdaterPlant.DataUpdater.Impl':'is_still_valid?' error, database_error

### ISSUE THREAD

**Issue by shortwavedave** [astarte-platform/astarte#609]
I am seeing what looks to be like a crash in the data-updater-plant. I've obfuscated some of the logs to hide device information, but left the garbled characters. It seems that once this log appears, then no device data across the network is available after that time. However, devices do not report any errors. We are running a somewhat old version of astarte, 0.10.2.

My feeling is that we accidentally inserted device info with bad characters and now the database is choking on it. Is there any way to remove this data so that this bad check stops happening? 

```
=CRASH REPORT==== 14-Jul-2021::16:11:10 ===
crasher:
initial call: Elixir.Astarte.DataUpdaterPlant.DataUpdater.Server:init/1
pid: <0.1680.0>
registered_name: []
exception error: no function clause matching
'Elixir.Astarte.DataUpdaterPlant.DataUpdater.Impl':'is_still_valid?'({error,
database_error},
nil) (lib/astarte_data_updater_plant/data_updater/impl.ex, line 529)
in function 'Elixir.Astarte.DataUpdaterPlant.DataUpdater.Impl':handle_data/6 (lib/astarte_data_updater_plant/data_updater/impl.ex, line 383)
in call from 'Elixir.Astarte.DataUpdaterPlant.DataUpdater.Server':handle_cast/2 (lib/astarte_data_updater_plant/data_updater/server.ex, line 53)
in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
in call from gen_server:handle_msg/6 (gen_server.erl, line 686)
ancestors: ['Elixir.Astarte.DataUpdaterPlant.AMQPDataConsumer',
'Elixir.Astarte.DataUpdaterPlant.Supervisor',<0.1548.0>]
message_queue_len: 299
messages: [{'$gen_cast',
{handle_data,<<"...">>,
<<"/.../d©ú? \eý?165/...">>,
<<16,0,0,0,1,118,0,51,51,51,51,51,51,23,64,0>>,
<<"test-utR7sB3nWEipxhwv-39C62F63E4C536-93409AC2">>,
16261980514207030}},
```

**Comment by shortwavedave** [comment]
Looks like the entire system is stuck because of this - any restarts of the container result in the same queue being processed and crashing

**Comment by bettio** [comment]
The quick and dirty way to get out of this situation is purging the queue from RabbitMQ admin UI or CLI while Data Updater Plant is not running (e.g. delete its pod and then purge the queue). Anyway we really suggest you to move forward to a supported version, such as 0.11 or 1.0.
**Beware: purging the queue may cause dataloss.**

**Comment by shortwavedave** [comment]
Thank you @bettio
