### ISSUE TITLE
Voyager Support Discontinued

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte#613]
**Starting from Dec 31, 2021 [it will be not possible to pull older Voyager docker images](https://blog.byte.builders/post/voyager-v2021.09.15/)**.

**Astarte Development Team is working on this issue and a release that doesn't depend on Voyager will be soon available (way before 31 December 2021).** This GitHub issue will be used to track related issues on this topic.

## Updated Plan
* Astarte 0.11: will be completely discontinued on 31 Dec 2021 and it will not receive any update
* Astarte 1.0: we are evaluating whether a feature back-port will be feasible without any disruption or major API change
* Astarte 1.1: will not depend on Voyager

**Comment by ike091** [comment]
Hi, is there currently any documentation on how to set up Astarte with the new nginx-based ingress? I have an older Astarte cluster that I am trying to replace such that it's not dependent on Voyager.

**Comment by matt-mazzucato** [comment]
Hi @ike091, we are currently working on the documentation. It will be available soon.
In the meantime, if you have any specific questions feel free to open an issue.

**Comment by bettio** [comment]
Since Astarte Kubernetes Operator 22.11.00 AVI is deprecated, and it will be removed starting from 23.05.00.
