### ISSUE TITLE
Error running Astarte in 5 minutes

### ISSUE THREAD

**Issue by arrowcircle** [astarte-platform/astarte#63]
Hey! I am trying to go through with 5 minutes tutorial, but I have a problem with test realm creation.

After generating a key, I run this command and get:

```
openssl rsa -in test_realm.key -pubout -outform PEM -out test_realm.key.pub
unable to load Private Key
4682208876:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.240.1/libressl-2.6/crypto/pem/pem_lib.c:683:Expecting: ANY PRIVATE KEY
```

I am running latest mac os x with openssl installed with brew:

```
openssl version
LibreSSL 2.6.5
```

How to properly deal with this problem?

**Comment by drf** [comment]
Hi, most likely it's ssh-keygen generating a key in a different format (I could reproduce on osx here).

Can you please try

`openssl genrsa -out test_realm.key`

instead of

`ssh-keygen -t rsa -b 4096 -f test_realm.key -N ''`

If this fixes your issue, then we'll modify the tutorial accordingly

**Comment by arrowcircle** [comment]
@drf this command works flawless! Thank you.
BTW, on the site there is no links on the documentation or github, this is very inconvenient

**Comment by drf** [comment]
Great! We'll update the doc today, thanks for opening this.
For the website - you're right, we're lagging quite behind. We're working on a new one hopefully in time/shortly after 0.10

**Comment by drf** [comment]
Docs updated in https://github.com/astarte-platform/docs/commit/aedb637fe268244611d75be12ebdb97b9336f3bd , github pages should sync shortly.
