### ISSUE TITLE
AppEngine: longinteger values can't be returned as string for some interface combinations

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#630]
AppEngine API supports passing some options that control how `longinteger` values are represented in JSON, due to the fact that 64 bit integer values are not theoretically representable using JSON numbers (since they're 64 floating point values, and the mantissa can only represent 52 bits) and some JSON decoders could fail if they encounter integers > 2^52.

To prevent that, `longinteger` values are returned as string by default, and it's possible to pass `allow_bigintegers=true` as query parameters to always render them as integers, or `allow_safe_bigintegers` to only render as integers the values which are < 2^52 (see [here](https://github.com/astarte-platform/astarte/blob/master/apps/astarte_appengine_api/lib/astarte_appengine_api/device/astarte_value.ex#L33)).

Currently though there are two cases where the behaviour is inconsistent: when [querying the root of an individual datastream interface](https://github.com/astarte-platform/astarte/blob/master/apps/astarte_appengine_api/lib/astarte_appengine_api/device/interface_values_options.ex) and [querying the root of an individual properties interface](https://github.com/astarte-platform/astarte/blob/master/apps/astarte_appengine_api/lib/astarte_appengine_api/device/interface_values_options.ex). Both those cases force `longinteger` values to be rendered as integers, and they ignore the passed options.

It should be possible to optionally change the current behaviour with query parameters, possibly leaving the current default as-is (even if it's inconsistent with the rest) to avoid API breaking changes.

**Comment by Annopaolo** [comment]
Closed by #687.
