### ISSUE TITLE
Unsets should always be considered successful

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#640]
This is related to #438, which fixed this for properties setting but didn't fix it for properties unset. For the same reason, unsets should always return `200 OK` regardless of the number of matches on the broker because:
- If a session is present, the unset will be sent when the device reconnects
- If a session is not present (or the device asks for a clean one on reconnect), the information of the unset path will be delivered by the `/control/consumerProperties` message.

Incidentally, there's currently another bug because the unset gets saved in the database _before_ checking the return value of `ensure_unset`, but this was not put in a separate issue because after this issue is fixed `ensure_unset` will always succeed by construction, thus making it always valid to save the value to the DB before it is sent.

Reported by @szakhlypa

**Comment by Annopaolo** [comment]
Closed by #691.
