### ISSUE TITLE
Replace dialyzex with dialyxir

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#667]
In astarte we started using [dialyzex](https://github.com/Comcast/dialyzex) instead of the more popular [dialyxir](https://github.com/jeremyjh/dialyxir) since it supported sharing Erlang and Elixir PLTs across projects and it cut analysis times when using it in multiple projects (like the Astarte microservices).

Now dialyxir supports PLT sharing too, so we might as well use that and enjoy the friendlier error messages.

**Comment by Annopaolo** [comment]
Closed by #697.
