### ISSUE TITLE
Handle all errors returned by the Realm Management backend instead of returning 500

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#683]
Currently Realm Management API does not handle many errors that can be returned, see e.g. [this](https://github.com/astarte-platform/astarte/blob/master/apps/astarte_realm_management/lib/astarte_realm_management/engine.ex#L639), [this](https://github.com/astarte-platform/astarte/blob/master/apps/astarte_realm_management/lib/astarte_realm_management/engine.ex#L645), or [this](e/blob/master/apps/astarte_realm_management/lib/astarte_realm_management/engine.ex#L653), failing instead with "500 Internal Server Error", which does not help the user much.

The way to handle those is adding a clause to the relevant controller (e.g. [TriggerController](https://github.com/astarte-platform/astarte/blob/master/apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/trigger_controller.ex#L42) for the ones linked above) and a render function in the relative View.

Once the clause is added, [this call](https://github.com/astarte-platform/astarte/blob/master/apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex#L240) actually succeeds (since the error atom is now existing in the application) and the error is correctly rendered.

**Comment by Annopaolo** [comment]
Closed by #686.
