### ISSUE TITLE
Communication issue between Astarte and Edgehog in a docker-compose-based setup

### ISSUE THREAD

**Issue by zr-her** [astarte-platform/astarte#732]
### What did I do?

I have created a docker-compose file combining the [Astarte part](https://github.com/astarte-platform/astarte/blob/master/docker-compose.yml) and the [Edgehog part](https://github.com/edgehog-device-manager/edgehog/blob/main/docker-compose.yml). I had to change the external port (4000) for the `edgehog-backend` service so that it doesn't conflict with the one for the `astarte-realm-management-api` service. 
I have also followed the steps in [Astarte in 5 minutes](https://docs.astarte-platform.org/1.0/010-astarte_in_5_minutes.html) as well as the [Edgehog initialization steps](https://edgehog-device-manager.github.io/docs/snapshot/deploying_with_kubernetes.html#edgehog-initialization)
### What did I get?
I am able to successfully login to the Astarte frontend and see the simulated connected device and the data it is streaming.
I am also able to login successfully to the Edgehog frontend. I can create system models and HW types successfully. However, the simulated device is not displayed there. 

I use the following as a `connection-trigger.json`:
```
{
    "name": "edgehog-connection",
    "action": {
        "http_url": "http://edgehog-backend:4000/tenants/test/triggers",
        "ignore_ssl_errors": false,
        "http_method": "post",
        "http_static_headers": {}
    },
    "simple_triggers": [
        {
            "type": "device_trigger",
            "on": "device_connected"
        }
    ]
}
```
When I replace the `http_url` above with a Mailgun Postbin URL, I am able to see the device connection event there. 

After some debugging, I realized the issue is probably related to the communication between Astarte and Edgehog. More specifically, the value used for `base_api_url`. For example, when inspecting the logs that occur after a device connects, I notice a HTTP GET request is sent to `<base_api_url>/appengine/v1/test/devices/<device_id>` which fails with a 404 error.
I tried different values for `base_api_url` e.g. `http://astarte-appengine-api:4002` or `http://astarte-realm-management-api:4000`, but all fail because the API paths are not correct. 

As for the logs for the `edgehog-backend` service, they show an error like the one documented in [this open issue](https://github.com/edgehog-device-manager/edgehog/issues/207).

Would there be a workaround to configure the `base_api_url` in a way that indicates that the astarte instance is running locally (e.g. via environment variables)? 

Please let me know if it is more appropriate to submit this ticket to the edgehog repository instead.

Thanks for your help!

**Comment by Pavinati** [comment]
The trigger you posted here is trying to send a message to "http://edgehog-backend:4000" but by default docker-compose files will use listen on localhost.
If you want to receive thoese triggers, you have to either use "localhost:4000" or define some domain resolution that will map "edgehog-backend" to the proper IP.
 A common aproach is to edit your hosts file, or setup some reverse proxy (with nginx or traefic) to make sure all the requests are redirected to the appropriate service.

**Comment by rbino** [comment]
Closing this since it has been answered
