### ISSUE TITLE
Realm Management error feedback when creating triggers with invalid URLs

### ISSUE THREAD

**Issue by Pavinati** [astarte-platform/astarte#748]
When installing a trigger with an invalid URL, Realm Management should return an error message specifying why the entity is not valid. Same as other fields in the Trigger.
eg:
```json
{"errors":{"name":["can't be blank"]}}
```

**Action:**
installing a trigger with an invalid `http_url`

**Expected result:**
```json
{"errors":{"http_url":["is not a valid URL"]}}
```

**Actual result:**
```json
{"errors":{}}
```

**Comment by Annopaolo** [comment]
Closed by #750.
