### ISSUE TITLE
Values of type `:datetime` inside a server owned object aggregated interface are not working

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#753]
6c19770894f85b13eb3f950da7e5718010a581d2 introduced the fix for values in individual interfaces, but it didn't fix the problem for object aggregated interfaces.

When sending a value, the API answers with:
```json
{"errors":{"detail":"Unexpected value type","expected_type":"datetime"}}
```

**Comment by Annopaolo** [comment]
Closed by #755.
