### ISSUE TITLE
Values of type `:binaryblob` inside a server owned object aggregated interface are handled incorrectly

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#754]
https://github.com/astarte-platform/astarte/commit/6c19770894f85b13eb3f950da7e5718010a581d2 introduced the fix for values in individual interfaces, but it didn't fix the problem for object aggregated interfaces.

This is related to #753 but it's more subtle: the API should expect base64 encoded values in the JSON payload, then it should decode them and then it should send the decoded value to the device (and save the decoded binary). It then should re-encode them when querying the value via the REST API.

With this bug, the first decoding was skipped when using a server-owned object aggregated interface containing a `binaryblob`.

This means that if a user sends
```json
{"data": {"binaryblob_endpoint": "YWJjZA=="}}
```
 (where `"YWJjZA=="` is `base64("abcd")`, the device will receive `"YWJjZA=="` instead of `"abcd"`. Moreover, when querying the value back, the API will send:
 ```json
{"data": {"binaryblob_endpoint": "WVdKalpBPT0="}}
 ``` 
where `"WVdKalpBPT0="` is `base64(base64("abcd"))`.

**Comment by Annopaolo** [comment]
Closed, too, by #755.
