### ISSUE TITLE
Expose docker-compose services with a single standard endpoint URL

### ISSUE THREAD

**Issue by davidebriani** [astarte-platform/astarte#761]
When running Astarte services via docker-compose, e.g. when following the *Astarte in 5 minutes* guide, the services are exposed via different dedicated endpoints.
This kind of setup could be improved to address the following points:
- The experience of using Astarte with docker-compose differs from the experience of usual deployments, e.g. with Kubernetes. This difference requires additional operational cost when migrating from a development environment to a production one.
- Integrating external services with Astarte could be an easier task if they could rely on a standard interface for Astarte services and if configuring a single endpoint would suffice to query all Astarte APIs.

**Comment by Annopaolo** [comment]
Closed by #768.
