### ISSUE TITLE
Change handler field name to an "error_handlers"

### ISSUE THREAD

**Issue by arahmarchak** [astarte-platform/astarte#762]
During working on adding support Trigger Delivery Policy reference to a Trigger, I tested api's for Policy and saw that i got an error on executing default JSON example. 

When i changed manually "handlers" string to an "error_handlers" it executes without earlier error. 

https://docs.astarte-platform.org/1.1/api/index.html?urls.primaryName=Realm%20Management%20API#/policy/installTriggerDeliveryPolicy

![before_execute](https://user-images.githubusercontent.com/34908857/225679766-2b2af3e5-0fef-49b3-9e7f-42f76403ba41.png)
![after_execute](https://user-images.githubusercontent.com/34908857/225679762-4fa68817-fd8f-4806-9812-93c72939f065.png)

**Comment by Annopaolo** [comment]
Closed by #763. Thank you @arahmarchak!
