### ISSUE TITLE
Allowed patterns could be added in interface schema

### ISSUE THREAD

**Issue by sorru94** [astarte-platform/astarte#851]
The fields `interface_name` and `endpoint` respectively belonging to the interface and mapping objects lack a formal definition of allowed patterns.
The regexes used in Astarte core to validate the fields could be added to the documentation.
Find them at:
1. https://github.com/astarte-platform/astarte_core/blob/4fcb19e67b5afcaeba569d28847a6756f017c3e2/specs/interface.json#L9
2. https://github.com/astarte-platform/astarte_core/blob/4fcb19e67b5afcaeba569d28847a6756f017c3e2/specs/mapping.json#L9

**Comment by Annopaolo** [comment]
Closed by #850.
