### ISSUE TITLE
Add support for Introspection change triggers

### ISSUE THREAD

**Issue by Pavinati** [astarte-platform/astarte#872]
Backends/Services that rely on a specific interface being supported have no other way to keep updated on the device introspection if not by polling each device (or the device list).
I would be great to be able to listen for device introspection change events like we do for connection/disconnection events

**Comment by Annopaolo** [comment]
In 1.1.0 support for introspection triggers has been added (see #731). It looks like your use case would be satisfied by an `incoming_introspection` trigger, something like:
```json
{
  "name": "incoming_introspection_trigger",
  "action": {
    "http_url": "https://your.given.url.bike",
    "http_method": "post"
  },
  "simple_triggers": [
    {
      "type": "device_trigger",
      "on": "incoming_introspection",
      "device_id": "<your device id>"
    }
  ]
}
```

The generated event has the following shape:
```json
{
    "introspection": "com.interface.org:0:1;org.interface.com:1:0",
    "type": "incoming_introspection"
}
```

**Comment by Annopaolo** [comment]
From Astarte 1.2 onward, the event will have a slightly different shape (you can go back to the old format, if needed), see #883:
```json
{
   "introspection":{
      "com.interface.org":{
         "major":0,
         "minor":1
      },
      "org.interface.com":{
         "major":1,
         "minor":0
      }
   },
   "type":"incoming_introspection"
}
```

**Comment by Pavinati** [comment]
That solves that issue for me! Thanks
