### ISSUE TITLE
Astarte Pairing API (swagger) contains incorrect examples

### ISSUE THREAD

**Issue by sorru94** [astarte-platform/astarte#907]
Some of the examples in the [Astarte pairing API swagger](https://docs.astarte-platform.org/astarte/latest/api/) contain incorrect payloads.
###  `/{realm_name}/devices/{hw_id}/protocols/astarte_mqtt_v1/credentials`
Response example is:
```json
{
  "data": {
    "client_certificate": "..."
  }
}
```
While it should be:
```json
{
  "data": {
    "client_crt": "..."
  }
}
```
###  `/{realm_name}/devices/{hw_id}/protocols/astarte_mqtt_v1/credentials/verify`
Request body example is:
```json
{
  "data": {
    "client_certificate": "..."
  }
}
```
While it should be:
```json
{
  "data": {
    "client_crt": "..."
  }
}
```
Response example is only showing the invalid case:
```json
{
  "data": {
    "valid": false,
    "cause": "INVALID_ISSUER"
  }
}
```
While it should also show the valid case:
```json
{
  "data": {
    "valid": true,
    "until": "2025-03-25 19:25:00.000Z"
  }
}
```

**Comment by Annopaolo** [comment]
Closed by #908.
